name: 'Sync Laravel Forge Deploy Script Action'
description: 'Updates your deploy script from a file under version control.'
author: 'ryanito'
branding:
  icon: arrow-up
  color: green
inputs:
  api_key:
    description: 'Laravel Forge API Key'
    required: true
  server_id:
    description: 'Laravel Forge Server ID'
    required: true
  site_id:
    description: 'Laravel Forge Site ID'
    required: true
  path:
    description: 'Path to your deploy script'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_KEY: ${{ inputs.api_key }}
    SERVER_ID: ${{ inputs.server_id }}
    SITE_ID: ${{ inputs.site_id }}
    PATH: ${{ inputs.path }}
